// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkCore2.Models;

public partial class ApplicationSettings
{
    public int Id { get; set; }

    public string AppName { get; set; }

    public int VersionMajor { get; set; }

    public int VersionMinor { get; set; }

    public int VersionBuild { get; set; }

    public int VersionRevison { get; set; }

    public int? Identifier { get; set; }

    public string TheVersion { get; set; }
}