// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using EntityFrameworkCore2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EntityFrameworkCore2.Data.Configurations;

public partial class ApplicationSettingsConfiguration : IEntityTypeConfiguration<ApplicationSettings>
{
    public void Configure(EntityTypeBuilder<ApplicationSettings> entity)
    {
        entity.HasKey(e => e.Id).HasName("PK_WebPageSettings1");

        entity.Property(e => e.AppName).IsRequired();
        entity.Property(e => e.TheVersion)
            .HasMaxLength(8000)
            .IsUnicode(false)
            .HasComputedColumnSql("((((((replace(str([VersionMajor]),' ','')+'.')+replace(str([VersionMinor]),' ',''))+'.')+replace(str([VersionBuild]),' ',''))+'.')+replace(str([VersionRevison]),' ',''))", false);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ApplicationSettings> entity);
}