// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConfigurationLibrary.Classes;
using EnityFrameworkCoreOffice.Models;
using Microsoft.EntityFrameworkCore;

namespace EnityFrameworkCoreOffice.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Office> Office { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConfigurationHelper.ConnectionString());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Office>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Office1");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("numeric(18, 0)");
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Computed)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComputedColumnSql("(case when [Id]<(9999) then 'OF'+right('000'+CONVERT([varchar],[Id],(10)),(4)) else 'OF'+CONVERT([varchar],[Id],(10)) end)", true);
            entity.Property(e => e.PostalCode).HasMaxLength(50);
            entity.Property(e => e.State).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}